name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./account/pom.xml
          mvn clean package -f ./income/pom.xml
          mvn clean package -f ./expense/pom.xml
          mvn clean package -f ./category/pom.xml
          mvn clean package -f ./cash/pom.xml

      - name: Docker Build and push for Account
        uses: docker/build-push-action@v4
        with:
          context: ./account
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/account:latest
            ghcr.io/${{ github.repository }}/account:${{ github.ref_name }}
            
      - name: Docker Build and push for Income
        uses: docker/build-push-action@v4
        with:
          context: ./income
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/income:latest
            ghcr.io/${{ github.repository }}/income:${{ github.ref_name }}
            
      - name: Docker Build and push for Expense
        uses: docker/build-push-action@v4
        with:
          context: ./expense
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/expense:latest
            ghcr.io/${{ github.repository }}/expense:${{ github.ref_name }}
            
      - name: Docker Build and push for Category
        uses: docker/build-push-action@v4
        with:
          context: ./category
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/category:latest
            ghcr.io/${{ github.repository }}/category:${{ github.ref_name }}
            
      - name: Docker Build and push for Cash
        uses: docker/build-push-action@v4
        with:
          context: ./cash
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cash:latest
            ghcr.io/${{ github.repository }}/cash:${{ github.ref_name }}
            
