server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: account
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/**, 
        - id: income
          uri: http://localhost:8083
          predicates:
            - Path=/incomes/**, 
        - id: expense
          uri: http://localhost:8084
          predicates:
            - Path=/expenses/**, 
        - id: category
          uri: http://localhost:8085
          predicates:
            - Path=/categorys/**, 
        - id: cash
          uri: http://localhost:8086
          predicates:
            - Path=/cashs/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: account
          uri: http://account:8080
          predicates:
            - Path=/account/**, 
        - id: income
          uri: http://income:8080
          predicates:
            - Path=/income/**, 
        - id: expense
          uri: http://expense:8080
          predicates:
            - Path=/expense/**, 
        - id: category
          uri: http://category:8080
          predicates:
            - Path=/category/**, 
        - id: cash
          uri: http://cash:8080
          predicates:
            - Path=/cash/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
