apiVersion: apps/v1
kind: Deployment
metadata:
  name: income
  labels:
    app: income
spec:
  replicas: 1
  selector:
    matchLabels:
      app: income
  template:
    metadata:
      labels:
        app: income
    spec:
      containers:
        - name: income
          image: yoojisuk0/income:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
